[project]
name = "scarab"
version = "0.1.0"
description = "Move your shit around"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "coloredlogs>=15.0.1",
    "logging>=0.4.9.6",
    "pandas>=2.2.3",
]
