#!/usr/bin/env bash

for system_path in /usr/local/sbin /usr/sbin /sbin; do
    case ":${PATH:-}:" in
        *":$system_path:"*) ;;
        *) PATH="${PATH:+$PATH:}$system_path" ;;
    esac
done
export PATH

die() {
    printf 'ERROR: %s\n' "$*" >&2
    exit 1
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"
}

validate_instance() {
    [[ "$1" =~ ^[a-z][a-z0-9-]*$ ]] ||
        die "Instance must match ^[a-z][a-z0-9-]*$: $1"
}

validate_ipv4_address() {
    local address="$1"
    local -a octets
    [[ "$address" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] ||
        die "Database bind address must be an IPv4 literal: $address"
    IFS=. read -r -a octets <<<"$address"
    local octet
    for octet in "${octets[@]}"; do
        ((10#$octet <= 255)) || die "Invalid IPv4 address: $address"
    done
    ((10#${octets[0]} != 0 && 10#${octets[0]} != 127 && 10#${octets[0]} < 224)) ||
        die "Database bind address must be a non-loopback unicast IPv4 address: $address"
}

validate_port() {
    local port="$1"
    [[ "$port" =~ ^[0-9]+$ ]] || die "Database port must be numeric: $port"
    ((10#$port >= 1 && 10#$port <= 65535)) ||
        die "Database port must be between 1 and 65535: $port"
}

resolve_db_bind_address() {
    require_command ip

    if [[ -z "$db_bind_address" ]]; then
        local -a addresses
        mapfile -t addresses < <(
            ip -4 -o addr show scope global |
                awk '{split($4, address, "/"); print address[1]}' |
                sort -u
        )
        case "${#addresses[@]}" in
            0)
                die "No non-loopback unicast IPv4 address is assigned to this host."
                ;;
            1)
                db_bind_address="${addresses[0]}"
                printf 'Automatically selected database bind address: %s\n' \
                    "$db_bind_address"
                ;;
            *)
                die "Multiple non-loopback unicast IPv4 addresses are assigned; pass --db-bind-address explicitly: ${addresses[*]}"
                ;;
        esac
    fi

    validate_ipv4_address "$db_bind_address"
    ip -4 -o addr show scope global |
        awk -v expected="$db_bind_address" \
            '{split($4, address, "/"); if (address[1] == expected) found=1} END {exit !found}' ||
        die "Database bind address is not assigned to this host: $db_bind_address"
}

configure_instance_paths() {
    instance="$1"
    validate_instance "$instance"

    etc_dir="/etc/$instance"
    config_dir="$etc_dir/config"
    compose_env="$etc_dir/compose.env"
    compose_file="$etc_dir/compose.yml"
    build_file="$etc_dir/compose.build.yml"
    runtime_env="$etc_dir/scarab.env"
    storage_mount_file="$etc_dir/storage-mount"
    postgres_dir="/var/lib/$instance/postgresql"
    storage_root="/srv/$instance"
    post_dir="$storage_root/post"
    get_dir="$storage_root/get"
    trash_dir="$storage_root/trash"
    log_dir="/var/log/$instance"
    backup_dir="/var/backups/$instance"
}

load_instance() {
    [[ "$(id -u)" -ne 0 ]] || die "Run lifecycle commands as the rootless service user, not root."
    [[ -r "$compose_env" ]] || die "Compose environment not readable: $compose_env"
    [[ -r "$compose_file" ]] || die "Compose file not readable: $compose_file"

    set -a
    # The file is generated by the root-only install command from validated values.
    # shellcheck disable=SC1090
    source "$compose_env"
    set +a

    local required_variable
    for required_variable in \
        SCARAB_ENVIRONMENT SCARAB_ENV_FILE SCARAB_CONFIG_DIR SCARAB_POSTGRES_DIR \
        SCARAB_POST_DIR SCARAB_GET_DIR SCARAB_TRASH_DIR SCARAB_LOG_DIR \
        SCARAB_DB_BIND_ADDRESS SCARAB_DB_PORT SCARAB_APP_IMAGE SCARAB_DB_IMAGE \
        SCARAB_BUILD_LOCAL; do
        [[ -n "${!required_variable:-}" ]] || die "$required_variable is missing from $compose_env"
    done

    [[ -r "$SCARAB_ENV_FILE" ]] || die "Runtime environment not readable: $SCARAB_ENV_FILE"
    [[ -r "$SCARAB_CONFIG_DIR/default_config.json" ]] || die "Default configuration is missing."
    grep -q '^POSTGRES_USER=' "$SCARAB_ENV_FILE" || die "POSTGRES_USER is missing."
    grep -q '^POSTGRES_PASSWORD=' "$SCARAB_ENV_FILE" || die "POSTGRES_PASSWORD is missing."
    grep -q '^POSTGRES_DB=' "$SCARAB_ENV_FILE" || die "POSTGRES_DB is missing."
    grep -q '^SCARAB_DB_PASSWORD=' "$SCARAB_ENV_FILE" || die "SCARAB_DB_PASSWORD is missing."
    ! grep -q 'CHANGE_ME' "$SCARAB_ENV_FILE" || die "Replace all CHANGE_ME values in $SCARAB_ENV_FILE"

    local postgres_user
    postgres_user="$(grep -m1 '^POSTGRES_USER=' "$SCARAB_ENV_FILE" | cut -d= -f2-)"
    postgres_user="${postgres_user%$'\r'}"
    postgres_user="${postgres_user#\"}"
    postgres_user="${postgres_user%\"}"
    postgres_user="${postgres_user#\'}"
    postgres_user="${postgres_user%\'}"
    [[ "$postgres_user" != "scarab_app" ]] ||
        die "POSTGRES_USER must be an administrative role distinct from scarab_app."

    local data_owner
    data_owner="$(stat -c '%U' "$SCARAB_POSTGRES_DIR")"
    [[ "$data_owner" == "$(id -un)" ]] ||
        die "$SCARAB_POSTGRES_DIR must be owned by $(id -un), currently $data_owner."
}

require_storage_mount() {
    [[ -e "$storage_mount_file" ]] || return 0
    require_command mountpoint

    local required_mount
    required_mount="$(<"$storage_mount_file")"
    [[ -n "$required_mount" ]] || die "Storage mount marker is empty: $storage_mount_file"
    mountpoint -q "$required_mount" || die "Required storage mount is unavailable: $required_mount"
}

compose() {
    PODMAN_COMPOSE_WARNING_LOGS=false \
        podman compose --env-file "$compose_env" -p "$instance" -f "$compose_file" "$@"
}

compose_with_build() {
    local source="$1"
    shift
    [[ -r "$build_file" ]] || die "Build Compose file not readable: $build_file"
    PODMAN_COMPOSE_WARNING_LOGS=false SCARAB_SOURCE_DIR="$source" podman compose \
        --env-file "$compose_env" -p "$instance" \
        -f "$compose_file" -f "$build_file" "$@"
}

container_id_for_service() {
    podman ps -a \
        --filter "label=com.docker.compose.project=$instance" \
        --filter "label=com.docker.compose.service=$1" \
        --format '{{.ID}}' | head -n 1
}

wait_for_database() {
    local attempt container_id health
    for ((attempt = 1; attempt <= 60; attempt++)); do
        container_id="$(container_id_for_service db)"
        if [[ -n "$container_id" ]]; then
            health="$(podman inspect --format '{{.State.Health.Status}}' "$container_id" 2>/dev/null || true)"
            [[ "$health" == "healthy" ]] && return 0
            [[ "$health" == "unhealthy" ]] && die "Database healthcheck failed."
        fi
        sleep 2
    done
    die "Database did not become healthy within 120 seconds."
}

provision_application_role() {
    compose exec -T db /usr/local/sbin/scarab-provision-app-role
}

wait_for_application() {
    local attempt container_id status
    for ((attempt = 1; attempt <= 30; attempt++)); do
        container_id="$(container_id_for_service app)"
        if [[ -n "$container_id" ]]; then
            status="$(podman inspect --format '{{.State.Status}}' "$container_id" 2>/dev/null || true)"
            [[ "$status" == "running" ]] && return 0
        fi
        sleep 1
    done
    die "Application did not reach the running state within 30 seconds."
}

verify_database_query() {
    local result
    result="$(compose exec -T db sh -c \
        'exec psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" --tuples-only --no-align --set=ON_ERROR_STOP=1 --command "SELECT 1;"')"
    result="${result%$'\r'}"
    [[ "$result" == "1" ]] || die "Database verification query returned an unexpected result: $result"
}

verify_database_publication() {
    local container_id publication expected
    container_id="$(container_id_for_service db)"
    [[ -n "$container_id" ]] || die "Database container was not found."
    publication="$(podman port "$container_id" 5432/tcp 2>/dev/null || true)"
    publication="${publication//$'\r'/}"
    expected="$SCARAB_DB_BIND_ADDRESS:$SCARAB_DB_PORT"
    grep -Fxq "$expected" <<<"$publication" ||
        die "PostgreSQL is not published at $expected (reported: ${publication:-none})."
}

verify_stack() {
    wait_for_database
    verify_database_query
    wait_for_application
    verify_database_publication
}

start_stack() {
    require_storage_mount
    compose config >/dev/null

    local db_container app_container existing_stack=false
    db_container="$(container_id_for_service db)"
    app_container="$(container_id_for_service app)"
    if [[ -n "$db_container" && -n "$app_container" ]]; then
        podman start "$db_container" >/dev/null
        existing_stack=true
    else
        if [[ -n "$db_container" || -n "$app_container" ]]; then
            compose down
        fi
        compose up -d
    fi

    wait_for_database
    provision_application_role
    if [[ "$existing_stack" == true ]]; then
        podman start "$app_container" >/dev/null
    fi
    verify_stack
    compose ps
}

stop_stack() {
    compose down
}

backup_database() {
    local timestamp target temporary
    timestamp="$(date -u +%Y%m%dT%H%M%SZ)"
    target="$backup_dir/scarab-$timestamp.dump"
    temporary="$target.tmp"
    umask 077
    # Variables are expanded by the shell inside the database container.
    # shellcheck disable=SC2016
    compose exec -T db sh -c \
        'exec pg_dump --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" --format=custom' \
        >"$temporary"
    mv "$temporary" "$target"
    printf 'Created backup: %s\n' "$target"
}